[2022-05-20 14:21:09,280] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_may_20_2022.choose_best_model manual__2022-05-20T14:21:07.177703+00:00 [queued]>
[2022-05-20 14:21:09,292] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_may_20_2022.choose_best_model manual__2022-05-20T14:21:07.177703+00:00 [queued]>
[2022-05-20 14:21:09,293] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-05-20 14:21:09,293] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-05-20 14:21:09,294] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-05-20 14:21:09,312] {taskinstance.py:1377} INFO - Executing <Task(BranchPythonOperator): choose_best_model> on 2022-05-20 14:21:07.177703+00:00
[2022-05-20 14:21:09,318] {standard_task_runner.py:52} INFO - Started process 362 to run task
[2022-05-20 14:21:09,321] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_may_20_2022', 'choose_best_model', 'manual__2022-05-20T14:21:07.177703+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmpuxab975e', '--error-file', '/tmp/tmp5jdq_r_r']
[2022-05-20 14:21:09,322] {standard_task_runner.py:80} INFO - Job 86: Subtask choose_best_model
[2022-05-20 14:21:09,382] {task_command.py:369} INFO - Running <TaskInstance: dag_may_20_2022.choose_best_model manual__2022-05-20T14:21:07.177703+00:00 [running]> on host 9764520d92aa
[2022-05-20 14:21:09,452] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_may_20_2022
AIRFLOW_CTX_TASK_ID=choose_best_model
AIRFLOW_CTX_EXECUTION_DATE=2022-05-20T14:21:07.177703+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-20T14:21:07.177703+00:00
[2022-05-20 14:21:09,464] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 207, in execute
    branch = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dags.py", line 16, in choose_best_ml_model
    best_accuracy =  max(accuracies)
ValueError: max() arg is an empty sequence
[2022-05-20 14:21:09,473] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=dag_may_20_2022, task_id=choose_best_model, execution_date=20220520T142107, start_date=20220520T142109, end_date=20220520T142109
[2022-05-20 14:21:09,483] {standard_task_runner.py:97} ERROR - Failed to execute job 86 for task choose_best_model (max() arg is an empty sequence; 362)
[2022-05-20 14:21:09,495] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-05-20 14:21:09,548] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
